"""add in room price and location

Revision ID: b052dafef727
Revises: 46f55731f1d3
Create Date: 2024-04-14 22:55:34.000026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b052dafef727'
down_revision: Union[str, None] = '46f55731f1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'location')
    op.drop_column('rooms', 'price')
    # ### end Alembic commands ###
