"""Add id into answer rule

Revision ID: 53f6aee68054
Revises: 10640e3c7cfd
Create Date: 2024-05-21 16:15:25.042745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f6aee68054'
down_revision: Union[str, None] = '10640e3c7cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answerrules', sa.Column('quest_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answerrules', 'questionrules', ['quest_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answerrules', type_='foreignkey')
    op.drop_column('answerrules', 'quest_id')
    # ### end Alembic commands ###
