"""new db

Revision ID: 1abb7ce042a7
Revises: 
Create Date: 2024-04-20 00:05:12.507493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1abb7ce042a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=True),
    sa.Column('telegram_tag', sa.String(length=60), nullable=True),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('date_deleted', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=False),
    sa.Column('date_deleted', sa.Date(), nullable=True),
    sa.Column('text', sa.String(length=400), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=False),
    sa.Column('date_disabled', sa.Date(), nullable=True),
    sa.Column('date_deleted', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=3000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=False),
    sa.Column('date_closed', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.Column('date_deleted', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roompictures',
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=False),
    sa.Column('date_disabled', sa.Date(), nullable=True),
    sa.Column('url_picture', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roompictures')
    op.drop_table('favorites')
    op.drop_table('deals')
    op.drop_table('rooms')
    op.drop_table('notifications')
    op.drop_table('user')
    # ### end Alembic commands ###
