"""Add name into room

Revision ID: 11c76267dfdb
Revises: eb3c2ba60d34
Create Date: 2024-05-24 13:48:23.926791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c76267dfdb'
down_revision: Union[str, None] = 'eb3c2ba60d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'name')
    # ### end Alembic commands ###
