"""Add more room info

Revision ID: c23afcba8cfc
Revises: 53f6aee68054
Create Date: 2024-05-24 13:24:14.946655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23afcba8cfc'
down_revision: Union[str, None] = '53f6aee68054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('floor_number', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('transport_info', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('time_check_in', sa.Time(), nullable=True))
    op.add_column('rooms', sa.Column('time_check_out', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'time_check_out')
    op.drop_column('rooms', 'time_check_in')
    op.drop_column('rooms', 'transport_info')
    op.drop_column('rooms', 'floor_number')
    op.drop_column('rooms', 'capacity')
    # ### end Alembic commands ###
