"""Change User

Revision ID: 74f4fd58ed34
Revises: dcc7cef77b53
Create Date: 2024-03-24 19:23:49.076069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f4fd58ed34'
down_revision: Union[str, None] = 'dcc7cef77b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deals', 'date_created',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('notifications', 'date_created',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('roompictures', 'date_created',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('rooms', 'date_created',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('users', sa.Column('hashed_password', sa.String(length=1024), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.alter_column('users', 'date_created',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('users', 'date_created',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.alter_column('rooms', 'date_created',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('roompictures', 'date_created',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('notifications', 'date_created',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('deals', 'date_created',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
