"""Reformat nullability is_front of RoomPicture

Revision ID: 040828f3de49
Revises: b8d51ad9b8f9
Create Date: 2024-05-26 14:30:15.608218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040828f3de49'
down_revision: Union[str, None] = 'b8d51ad9b8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roompictures', 'is_front',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roompictures', 'is_front',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
