"""Add answers others logic

Revision ID: b8d51ad9b8f9
Revises: 11c76267dfdb
Create Date: 2024-05-24 20:47:27.829800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d51ad9b8f9'
down_revision: Union[str, None] = '11c76267dfdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionothers',
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answerothers',
    sa.Column('question_other_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_other_id'], ['questionothers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('useranswerothers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer_other_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_other_id'], ['answerothers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useranswerothers')
    op.drop_table('answerothers')
    op.drop_table('questionothers')
    # ### end Alembic commands ###
