"""create possible interests

Revision ID: dee8bafa78de
Revises: 586950285694
Create Date: 2024-05-20 19:09:46.590758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import ForeignKey

# revision identifiers, used by Alembic.
revision: str = 'dee8bafa78de'
down_revision: Union[str, None] = '586950285694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionrules',
    sa.Column('description_rule', sa.String(length=100), nullable=False),
    sa.Column('description_interest', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rules',
                  sa.Column('room_rule_id', sa.Integer(), ForeignKey("questionrules.id"), nullable=True)
                  )
    op.add_column('rules', sa.Column('description_rule', sa.String(length=100), nullable=False))
    op.add_column('rules', sa.Column('description_interest', sa.String(length=100), nullable=False))
    op.create_table('useranswerrules',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useranswerrules')
    op.drop_table('roomrules')
    op.drop_table('rules')
    op.drop_table('questionrules')
    # ### end Alembic commands ###
