"""ad is front flag for picture

Revision ID: 10640e3c7cfd
Revises: 1fb20c67d85c
Create Date: 2024-05-21 00:28:04.222744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10640e3c7cfd'
down_revision: Union[str, None] = '1fb20c67d85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roompictures', sa.Column('is_front', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roompictures', 'is_front')
    # ### end Alembic commands ###
